from PySide6.QtGui import QIcon, QPixmap
from filecatman.core.objects import ÆIconTheme, ÆIconList
from filecatman.core.functions import getÆDirPath


def getDefaultIconsList():
    dirPath = getÆDirPath()
    
    iconsList = ÆIconList()
    iconsList.setFallbackNames(dict(
        Tag=dirPath+"data/icons/tag.png",
        About=dirPath+"data/icons/hicolor/128x128/apps/filecatman.png"
    ))
    iconsList.setPixmapNames((
        'XMLImport', 'XMLExport', 'TXTImport', 'Success', 'Failure', 'SymbolicLink', 'New', 'Open',
    ))

    iconsList.icons['NullIcon'] = QIcon()
    iconsList.icons['Filecatman'] = QIcon(dirPath+"data/icons/hicolor/128x128/apps/filecatman.png")
    iconsList.pixmaps['Filecatman'] = QPixmap(dirPath+"data/icons/hicolor/128x128/apps/filecatman.png")
    iconsList.pixmaps['Filecatman48'] = QPixmap(iconsList.icons['Filecatman'].pixmap(48))
    iconsList.icons['Qt'] = QIcon(dirPath+"data/icons/qt-logo.png")

    defaultTheme = ÆIconTheme('System Default')
    defaultTheme.setIconPaths(dict(
        DatabaseNew="document-new",
        DatabaseOpen="document-open",
        New="document-new",
        Open="document-open",
        DatabaseClose="document-close",
        DatabaseDrop="user-trash-full",
        DatabaseInfo="server-database",
        Exit="exit",
        About="help-about",
        Add="list-add",
        Add2="list-add",
        Edit="document-edit",
        Remove="list-remove",
        Refresh="view-refresh",
        Play="media-playback-start",
        Preferences="preferences-system",
        Details="document-properties",
        DetailsEdit="document-properties",
        Options="preferences-other",
        Relations="x-office-address-book",
        RelationsEdit="address-book-new",
        Fullscreen="view-fullscreen",
        Items='package-x-generic',
        Categories='bookmarks',
        Document='application-pdf',
        Webpage='text-html',
        Weblink='starred',
        Image='image-x-generic',
        Video='video-x-generic',
        Audio='audio-x-generic',
        Author='face-glasses',
        Subject='accessories-dictionary',
        Nation='globe',
        Group='system-users',
        Event='x-office-calendar',
        Tag='feed-subscribe',
        Publisher='view-pim-news',
        Person='face-smile',
        Search='system-search',
        Execute='system-run',
        CheckAll='dialog-ok',
        CheckNone='edit-clear',
        Clear='edit-clear',
        CheckInverse='rotate',
        Import='document-import',
        Export='document-export',
        XMLImport='text-xml',
        XMLExport='text-xml',
        TXTImport='text-x-generic',
        Warning='emblem-danger',
        FileChecker='system-devices-panel-alert',
        Folder='user-home',
        Success='dialog-ok',
        Failure='dialog-error',
        SymbolicLink='emblem-symbolic-link',
        Up='go-up',
        Down='go-down',
        Forward='go-next',
        Backward='go-previous',
        MimeApp='application-x-executable',
        MimeSwf='application-x-flash-video',
        MimePres='x-office-presentation',
        MimeSpre='x-office-spreadsheet',
        FileManager='system-file-manager',
        Cut='edit-cut',
        Copy='edit-copy',
        Paste='edit-paste',
        SelectAll='edit-select-all',
        HelpContents='help-contents',
        Contents='go-home',
        Find='edit-find',
        Undo='edit-undo',
        Redo='edit-redo'
    ))
    defaultTheme.setIconAlternatives(dict(
        DatabaseInfo=('ooo-base', "help-about",),
        DatabaseClose=("window-close",),
        Exit=("application-exit",),
        Remove=("edit-delete",),
        Import=('text-x-generic',),
        Export=('text-x-generic',),
        XMLImport=('text-html', 'internet-web-browser'),
        XMLExport=('text-html', 'internet-web-browser'),
        Edit=("gtk-edit", "stock_edit", "accessories-text-editor",),
        Nation=('applications-internet', 'internet-web-browser', 'text-html',),
        Group=('emblem-shared',),
        Person=('user-identity',),
        Author=('face-cool', 'user-identity',),
        Publisher=('x-office-document',),
        Weblink=('favorites', 'emblem-favorite'),
        FileChecker=('debug-run', 'package-x-generic'),
        Categories=('view-catalog', 'view-categories', 'user-bookmarks'),
        Document=('x-office-document',),
        Warning=('dialog-warning', 'dialog-error'),
        Success=('dialog-information',),
        CheckAll=('edit-select-all', 'checkbox', 'gtk-ok', 'emblem-ok'),
        SelectAll=('checkbox', 'dialog-ok', 'gtk-ok', 'emblem-ok'),
        Tag=('easytag',),
        Folder=('folder',),
        Contents=('go-first',),
        Find=('system-search',)
    ))
    defaultTheme.isSystemTheme = True
    iconsList.appendIconTheme(defaultTheme)

    prettyOfficeTheme = ÆIconTheme('Pretty Office')
    prettyOfficeTheme.setIconPaths(dict(
        DatabaseNew=dirPath+"data/icons/prettyOffice/Add-to-database32.png",
        DatabaseOpen=dirPath+"data/icons/prettyOffice/open-file32.png",
        New=dirPath+"data/icons/prettyOffice/Add-to-database32.png",
        Open=dirPath+"data/icons/prettyOffice/open-file32.png",
        DatabaseClose=dirPath+"data/icons/prettyOffice/database-close.png",
        DatabaseDrop=dirPath+"data/icons/prettyOffice/Trash-can32.png",
        DatabaseInfo=dirPath+"data/icons/prettyOffice/Basic-data.png",
        Exit=dirPath+"data/icons/prettyOffice/close32.png",
        About=dirPath+"data/icons/prettyOffice/info32.png",
        Add=dirPath+"data/icons/prettyOffice/add232.png",
        Add2=dirPath+"data/icons/prettyOffice/add132.png",
        Edit=dirPath+"data/icons/prettyOffice/edit32.png",
        Remove=dirPath+"data/icons/prettyOffice/delete232.png",
        Refresh=dirPath+"data/icons/prettyOffice/Refresh32.png",
        Play=dirPath+"data/icons/prettyOffice/Continue32.png",
        Preferences=dirPath+"data/icons/prettyOffice/Maintenance32.png",
        Details=dirPath+"data/icons/prettyOffice/Order-history32.png",
        DetailsEdit=dirPath+"data/icons/prettyOffice/Ordering32.png",
        Options=dirPath+"data/icons/prettyOffice/configure32.png",
        Relations=dirPath+"data/icons/prettyOffice/addressbook32.png",
        RelationsEdit=dirPath+"data/icons/prettyOffice/addressbook-edit32.png",
        Fullscreen=dirPath+"data/icons/prettyOffice/computer32.png",
        Items=dirPath+'data/icons/prettyOffice/Product32.png',
        Categories=dirPath+'data/icons/prettyOffice/Binary-tree32.png',
        Document=dirPath+'data/icons/prettyOffice/PDF32.png',
        Webpage=dirPath+'data/icons/prettyOffice/Globe32.png',
        Weblink=dirPath+'data/icons/prettyOffice/Link32.png',
        Image=dirPath+'data/icons/prettyOffice/Insert-image32.png',
        Video=dirPath+'data/icons/prettyOffice/Video-file.png',
        Audio=dirPath+'data/icons/prettyOffice/Audio-file.png',
        Author=dirPath+'data/icons/prettyOffice/Prefessor32.png',
        Subject=dirPath+'data/icons/prettyOffice/Library.png',
        Nation=dirPath+'data/icons/prettyOffice/Globe32.png',
        Group=dirPath+'data/icons/prettyOffice/family32.png',
        Event=dirPath+'data/icons/prettyOffice/calenda32.png',
        Tag=dirPath+'data/icons/prettyOffice/sale.png',
        Publisher=dirPath+'data/icons/prettyOffice/Announcements32.png',
        Person=dirPath+'data/icons/prettyOffice/Man.png',
        Search=dirPath+'data/icons/prettyOffice/Search.png',
        Execute=dirPath+'data/icons/prettyOffice/Wheel32.png',
        CheckAll=dirPath+'data/icons/prettyOffice/Success.png',
        CheckNone=dirPath+'data/icons/prettyOffice/clear32.png',
        Clear=dirPath+'data/icons/prettyOffice/clear32.png',
        CheckInverse=dirPath+'data/icons/prettyOffice/Order32.png',
        Import=dirPath+'data/icons/prettyOffice/import32.png',
        Export=dirPath+'data/icons/prettyOffice/export32.png',
        XMLImport=dirPath+'data/icons/prettyOffice/Xml-tool32.png',
        XMLExport=dirPath+'data/icons/prettyOffice/Xml-tool32.png',
        TXTImport=dirPath+'data/icons/prettyOffice/import32.png',
        Warning=dirPath+'data/icons/prettyOffice/warning32.png',
        FileChecker=dirPath+'data/icons/prettyOffice/search-good.png',
        Folder=dirPath+'data/icons/prettyOffice/Folder.png',
        Success=dirPath+'data/icons/prettyOffice/Success.png',
        Failure=dirPath+'data/icons/prettyOffice/close32.png',
        SymbolicLink=dirPath+'data/icons/prettyOffice/Symlink.png',
        Up=dirPath+'data/icons/prettyOffice/up32.png',
        Down=dirPath+'data/icons/prettyOffice/down32.png',
        Forward=dirPath+'data/icons/prettyOffice/forward32.png',
        Backward=dirPath+'data/icons/prettyOffice/back32.png',
        MimeSwf=dirPath+'data/icons/prettyOffice/SWF32.png',
        FileManager='',
        Cut=dirPath+'data/icons/prettyOffice/cut32.png',
        Copy=dirPath+'data/icons/prettyOffice/copy32.png',
        Paste=dirPath+'data/icons/prettyOffice/Paste32.png',
        SelectAll=dirPath+'data/icons/prettyOffice/Success.png',
        HelpContents=dirPath+'data/icons/prettyOffice/Faq.png',
        Contents=dirPath+'data/icons/prettyOffice/Content32.png',
        Find=dirPath+'data/icons/prettyOffice/Search.png',
        Undo=dirPath+'data/icons/prettyOffice/Undo32.png',
        Redo=dirPath+'data/icons/prettyOffice/Redo32.png'
    ))
    iconsList.appendIconTheme(prettyOfficeTheme)

    farmFreshTheme = ÆIconTheme('Farm Fresh')
    farmFreshTheme.setIconPaths(dict(
        DatabaseNew=dirPath+"data/icons/farmFresh/database_add.png",
        DatabaseOpen=dirPath+"data/icons/farmFresh/folder_database.png",
        New=dirPath+"data/icons/farmFresh/database_add.png",
        Open=dirPath+"data/icons/farmFresh/folder_database.png",
        DatabaseClose=dirPath+"data/icons/farmFresh/cancel.png",
        DatabaseDrop=dirPath+"data/icons/farmFresh/bin.png",
        DatabaseInfo=dirPath+"data/icons/farmFresh/database.png",
        Exit=dirPath+"data/icons/farmFresh/door.png",
        About=dirPath+"data/icons/farmFresh/information.png",
        Add=dirPath+"data/icons/farmFresh/plus.png",
        Add2=dirPath+"data/icons/farmFresh/add.png",
        Edit=dirPath+"data/icons/farmFresh/pencil.png",
        Remove=dirPath+"data/icons/farmFresh/cross.png",
        Refresh=dirPath+"data/icons/farmFresh/update.png",
        Play=dirPath+"data/icons/farmFresh/control_play_blue.png",
        Preferences=dirPath+"data/icons/farmFresh/setting_tools.png",
        Details=dirPath+"data/icons/farmFresh/document_properties.png",
        DetailsEdit=dirPath+"data/icons/farmFresh/document_prepare.png",
        Options=dirPath+"data/icons/farmFresh/wrench.png",
        Relations=dirPath+"data/icons/farmFresh/book_addresses.png",
        RelationsEdit=dirPath+"data/icons/farmFresh/book_addresses.png",
        Fullscreen=dirPath+"data/icons/farmFresh/widescreen.png",
        Items=dirPath+'data/icons/farmFresh/package.png',
        Categories=dirPath+'data/icons/farmFresh/categories.png',
        Document=dirPath+'data/icons/farmFresh/file_extension_pdf.png',
        Webpage=dirPath+'data/icons/farmFresh/file_extension_html.png',
        Weblink=dirPath+'data/icons/farmFresh/link.png',
        Image=dirPath+'data/icons/farmFresh/picture.png',
        Video=dirPath+'data/icons/farmFresh/video.png',
        Audio=dirPath+'data/icons/farmFresh/music.png',
        Author=dirPath+'data/icons/farmFresh/user_oldman.png',
        Subject=dirPath+'data/icons/farmFresh/bookshelf.png',
        Nation=dirPath+'data/icons/farmFresh/world.png',
        Group=dirPath+'data/icons/farmFresh/group.png',
        Event=dirPath+'data/icons/farmFresh/date.png',
        Tag=dirPath+'data/icons/farmFresh/three_tags.png',
        Publisher=dirPath+'data/icons/farmFresh/newspaper.png',
        Person=dirPath+'data/icons/farmFresh/user.png',
        Search=dirPath+'data/icons/farmFresh/magnifier.png',
        Execute=dirPath+'data/icons/farmFresh/cog.png',
        CheckAll=dirPath+'data/icons/farmFresh/check_box.png',
        CheckNone=dirPath+'data/icons/farmFresh/check_box_uncheck.png',
        Clear=dirPath+'data/icons/farmFresh/textfield_clear.png',
        CheckInverse=dirPath+'data/icons/farmFresh/check_box_mix.png',
        Import=dirPath+'data/icons/farmFresh/document_import.png',
        Export=dirPath+'data/icons/farmFresh/document_export.png',
        XMLImport=dirPath+'data/icons/farmFresh/xml_imports.png',
        XMLExport=dirPath+'data/icons/farmFresh/xml_exports.png',
        TXTImport=dirPath+'data/icons/farmFresh/text_imports.png',
        Warning=dirPath+'data/icons/farmFresh/error.png',
        FileChecker=dirPath+'data/icons/farmFresh/data_validation.png',
        Folder=dirPath+'data/icons/farmFresh/folder.png',
        Success=dirPath+'data/icons/farmFresh/tick.png',
        Failure=dirPath+'data/icons/farmFresh/cancel.png',
        SymbolicLink=dirPath+'data/icons/farmFresh/file_extension_lnk.png',
        Up=dirPath+'data/icons/farmFresh/arrow_up.png',
        Down=dirPath+'data/icons/farmFresh/arrow_down.png',
        Forward=dirPath+'data/icons/farmFresh/arrow_right.png',
        Backward=dirPath+'data/icons/farmFresh/arrow_left.png',
        MimeApp=dirPath+'data/icons/farmFresh/file_extension_exe.png',
        MimeSwf=dirPath+'data/icons/farmFresh/file_extension_swf.png',
        MimePres=dirPath+'data/icons/farmFresh/file_extension_pps.png',
        FileManager=dirPath+'data/icons/farmFresh/file_manager.png',
        Cut=dirPath+'data/icons/farmFresh/cut.png',
        Copy=dirPath+'data/icons/farmFresh/page_copy.png',
        Paste=dirPath+'data/icons/farmFresh/page_paste.png',
        SelectAll=dirPath+'data/icons/farmFresh/table_select_all.png',
        HelpContents=dirPath+'data/icons/farmFresh/help.png',
        Contents=dirPath+'data/icons/farmFresh/restaurant_menu.png',
        Find=dirPath+'data/icons/farmFresh/magnifier.png',
        Undo=dirPath+'data/icons/farmFresh/undo.png',
        Redo=dirPath+'data/icons/farmFresh/redo.png'
    ))
    iconsList.appendIconTheme(farmFreshTheme)

    return iconsList